# Generated by cucumber-sinatra. (2014-07-28 10:21:42 +0100)

ENV['RACK_ENV'] = 'test'
ENV['DATABASE_URL'] = "postgres://ohujkjsphlzsfl:RqUQR7BEyl2d3_GxJUTFc-eKmG@ec2-54-197-241-82.compute-1.amazonaws.com:5432/dfb13astcg6b47"
ENV['MAILGUN_API_KEY'] = "key-1ctxo78pq5kb65kxbm3-4beu7etqa2c4"

require File.join(File.dirname(__FILE__), '..', '..', 'lib/bookmark_manager.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = BookmarkManager

class BookmarkManagerWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BookmarkManagerWorld.new
end
